# Generated by Django 5.1.4 on 2024-12-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_alter_exeatrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='department',
            field=models.CharField(blank=True, choices=[('Accounting', 'Accounting'), ('Biochemistry', 'Biochemistry'), ('Biotechnology', 'Biotechnology'), ('Business Administration', 'Business Administration'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('International Relations', 'International Relations'), ('Law', 'Law'), ('Mass Communication', 'Mass Communication'), ('Mathematics', 'Mathematics'), ('Medical Lab Science', 'Medical Lab Science'), ('Microbiology', 'Microbiology'), ('Nursing', 'Nursing'), ('Physiotherapy', 'Physiotherapy'), ('Political Science', 'Political Science'), ('Public Health', 'Public Health')], max_length=50, null=True),
        ),
    ]
