# Generated by Django 5.1.4 on 2024-12-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeatrequest',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=10),
        ),
    ]
